export const GET_ALL_PRODUCTS = "GET_STUDENTS_DATA";
export const MARK_ATTENDANCE = "MARK_ATTENDANCE";
export const MARK_ALL_ATTENDANCE = "MARK_ALL_ATTENDANCE";
export const UNMARK_ATTENDANCE = "UNMARK_ATTENDANCE";
export const UNMARK_ALL_ATTENDANCE = "UNMARK_ALL_ATTENDANCE";
export const ADD_COMMENT = "ADD_COMMENT";
export const LEAVE_OF_ABSENCE = "LEAVE_OF_ABSENCE";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const MARK_ALL_SELECTED_ATTENDANCE = "MARK_ALL_SELECTED_ATTENDANCE";
export const ADD_SELECTED_COMMENT = "ADD_SELECTED_COMMENT";
export const UNMARK_SELECTED_ATTENDANCE = "UNMARK_SELECTED_ATTENDANCE";

export const SET_CALENDAR_DATE = "SET_CALENDAR_DATE";
export const SET_TODAYS_DATE = "SET_TODAYS_DATE";
export const FORWARD_MONTH = "FORWARD_MONTH";
export const FORWARD_WEEK = "FORWARD_WEEK";
export const BACKWARD_WEEK = "BACKWARD_WEEK";
export const BACKWARD_MONTH = "BACKWARD_MONTH";
